### ISSUE TITLE
BUG: Cepstrum not computed correctly in vocalpy.spectral.sat

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vocalpy#122]
**Describe the bug**
`vocalpy.spectral.sat` is a translation to Python of the [SAT code](http://soundanalysispro.com/matlab-sat).
SAT uses the matlab function [`rceps`](https://www.mathworks.com/help/signal/ref/rceps.html) to compute the cepstrum. As indicated in the pseudocode in the Matlab docs, this is done by computing the inverse FFT of the log *of the magnitude* of the spectrum. This is basically the matlab version of the algorithm described in the book they cite:
![image](https://github.com/vocalpy/vocalpy/assets/11934090/b510c648-f368-4b1f-9180-64a7bfdf321a)

The SAT code specifically uses use one of the two sets of spectra computed for a multi-taper spectrogram.

from line 116 of SAT_sound.m
```matlab
                    window1=window.*tapers(:,1);
                    window2=window.*tapers(:,2);
                    % compute the cepstrum: 
                    if any(window1)
                        tmp=rceps(window1);
                    else
                        tmp=zeros(length(window1),1);
                    end

```

We correctly use the fft of `window1`; in our code it becomes `spectra1`.  
But what we do *not* do is take the absolute value of `spectra1`. 
https://github.com/vocalpy/vocalpy/blob/8b85eed0dee76e3aa47599dd99f3fb7f6fc3ccbe/src/vocalpy/spectral/sat.py#L113

```python
    log_spectra = np.log(spectra1, where=spectra1 > 0)
    cepstrogram = np.fft.ifft(log_spectra, n=n_fft).real
```

And this actually leads to pretty big differences in values.
From an interactive session:
```python
>>> cepstrum = np.fft.ifft(np.log(spectra1))
>>> cepstrum_abs = np.fft.ifft(np.log(np.abs(spectra1))
>>> cepstrum[0, :10]
array([-5.88668039,  0.03902181,  0.25015098,  0.14409216,  0.22280241,
        0.10110034,  0.14784462,  0.14013646, -0.01752208,  0.01025931])
>>> cepstrum_abs[0, :10]
array([-5.88668039,  0.21275828,  0.25227263,  0.20196257,  0.13223225,
        0.10026057,  0.16990165,  0.08894541, -0.00986346,  0.07404688])
```

I think this is because `np.log` behaves differently for complex values
> For complex-valued input, [log](https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log) is a complex analytical function that has a branch cut [-inf, 0] and is continuous from above on it.
Since we don't use `np.abs` to get the magnitude, we're getting the behavior of `np.log` for the complex-valued FFT that we compute.

So what we should do to correctly replicate `rceps` is to take the absolute value of that first set of spectra.

As further confirmation, `python-acoustics` does just that:
https://github.com/python-acoustics/python-acoustics/blob/99d79206159b822ea2f4e9d27c8b2fbfeb704d38/acoustics/cepstrum.py#L146
```python
    spectrum = np.fft.fft(x, n=n)
    ceps = np.fft.ifft(np.log(np.abs(spectrum))).real
```

@ralphpeterson just a heads up that this might affect you if you are using SAT features, namely goodness of pitch. I will go ahead and make this quick fix and then release a new version

**Comment by ralphpeterson** [comment]
Nice catch, thanks for the quick fix!

Have we compared vocalpy.spectral.sat outputs to SAT outputs using the same dataset?

**Comment by NickleDave** [comment]
We haven't, I have definitely thought about it.
https://github.com/PaulEcoffet/birdsonganalysis/issues/1#issuecomment-376214452
https://github.com/vocalpy/sappy/issues/4
https://github.com/vocalpy/vocalpy/issues/81#issue-2013437680

If I were to do it now, I would use the "zebra-finch-wav" data in the "source" data we use for testing, here: https://osf.io/45brw/, which is taken from https://github.com/PaulEcoffet/birdsonganalysis/tree/master/songs.
I *think* the subset of songs that I put in the source data were originally on the SAP site.

We'd need:
- [ ] a Matlab script that runs SAT on all those songs and then saves the extracted features specifically, e.g. to .mat files we can load with `scipy.io.loadmat`
- [ ] a Python script that runs `vocalpy.feature.sat` on the same data and saves the features. Easiest way here might be to run `vocalpy.feature.sat.similarity_features` then dump the returned `xarray.Dataset` to zarr
- [ ] unit tests in `tests/test_feature/test_sat` that at least test whether the output of `vocalpy.feature.sat.similarity_features` has changed, i.e. a kind of regression test

I'm in the middle of renaming/rewriting the `Audio` class as a `Sound` class that can properly handle multi-channel audio (see #90). But once that is merged in this would be do-able.
