### ISSUE TITLE
BUG: vak and vocalpy does not requiere the same version of crowsetta

### ISSUE THREAD

**Issue by neuronalX** [vocalpy/vocalpy#38]
Installing vocalpy with pip after vak generates the following problem in dependencies:
> pip install vak
...
> pip install vocalpy
....
Installing collected packages: msgpack, appdirs, wrapt, typeguard, threadpoolctl, soxr, pydantic, mypy-extensions, multimethod, llvmlite, lazy-loader, importlib-resources, greenlet, decorator, audioread, typing-inspect, SQLAlchemy, scikit-learn, pooch, numba, pandera, librosa, crowsetta, vocalpy
  Attempting uninstall: crowsetta
    Found existing installation: crowsetta 3.4.1
    Uninstalling crowsetta-3.4.1:
      Successfully uninstalled crowsetta-3.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vak 0.8.1 requires crowsetta<4.0.0,>=3.4.0, but you have crowsetta 5.0.0 which is incompatible.

Then, installing tweetynet reverts the version of crowsetta:
> pip install tweetynet
Installing collected packages: crowsetta, tweetynet
  Attempting uninstall: crowsetta
    Found existing installation: crowsetta 5.0.0
    Uninstalling crowsetta-5.0.0:
      Successfully uninstalled crowsetta-5.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vocalpy 0.3.0 requires crowsetta>=5.0.0, but you have crowsetta 3.4.1 which is incompatible.

**Comment by NickleDave** [comment]
Thanks for catching this @neuronalX -- it will be fixed after https://github.com/vocalpy/vak/issues/526 gets into the next release of vak. Cross-referencing here to make sure we catch it

**Comment by NickleDave** [comment]
This was fixed by https://github.com/vocalpy/vak/pull/657. Thank you again @neuronalX for the gentle reminder to actually do it!
